// INSTANCIA DE JARVIS
let Jarvis = new Artyom(), respuestaMode = 'quick', timeouts = [], freeSayFlag = false;

const commands = {
  saludos: ['Hola', 'hola', 'Holi', 'Buenos dias', 'Buenas tardes', 'Buenas noches', 'Buenas', 'Hello', 'Hi', 'Good Morning', 'Good afternoon', 'Good night'],
  modoReposo: ['reposo'],
  modoFrasesLentas: ['lento', 'cortas', 'lento'], // En pruebas(versión beta)
  modoFrasesNormales: ['normal', 'normales', 'normal'], // En pruebas(versión beta)
  modoFrasesLargas: ['largo', 'largas', 'rapido'],
  silenciar: ['silencio', 'callate'], // En pruebas(versión beta)
  galeriasysecciones: ['galerias', 'galerias y secciones', 'Galerías', 'Galerías y secciones', 'Secciones'], //7
  siMeGustariaOirMas: ['si me gustaría', 'si gracias', 'Me gustaría'],
  noMeGustariaOirMas: ['En otro momento', 'Mejor luego', 'Por ahora no', 'No, de momento'],
  espaciosyarquitectura: ['Espacios', 'Espacios y arquitectura', 'Arquitectura'], // 11
  historia: ['Historia de Arco', 'Arco', 'Historia'],
  novedadesDosMilVeintiDos: ['Novedades 2022', 'Novedades', '2022'],
  puntuacion: ['Uno', 'dos', 'Tres', 'Cuatro', 'Cinco']
}

let videoDinamicSrcArr = [
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/1.saludos/saludo_chica_1.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/1.saludos/saludo_chica_2.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/2.galerias/cua_uno/40MASUNO_1.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/2.galerias/cua_uno/40MASUNO_2.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/2.galerias/nunca_mismo/NUNCA1.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/2.galerias/nunca_mismo/NUNCA2.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/2.galerias/opening/OPENING_1.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/2.galerias/opening/OPENING_2.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/2.galerias/p.artistas/p.artistas.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/2.galerias/p.general/p.general.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/2.galerias/p.general/p.general_2.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/3.arquitectura/arco/fundacion_1.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/3.arquitectura/arco/fundacion_2.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/3.arquitectura/espacios/espacios_1.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/3.arquitectura/espacios/espacios_2_3.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/3.arquitectura/p.general/p.general.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/3.arquitectura/sala_cua_uno/sala_cua_uno.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/3.arquitectura/sala_vip/sala_vip.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/3.arquitectura/terraza/terraza.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/4.historia/historia_1.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/4.historia/historia_2.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/4.historia/historia_3.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/5.novedades/novedades_1.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/5.novedades/novedades_2.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/5.novedades/novedades_3.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/6.OtraTematicaChica/OtraTematicaChica.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/7.respuesta_si/respuesta_si.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/8.pregunta_abierta/pregunta_abierta.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/9.puntuacion/puntuacion.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/10.despedidas/despedida_1.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chica/10.despedidas/despedida_2.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/reposo_chico/reposo_chico.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/1.saludos/saludo_1.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/1.saludos/saludo_2.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/2.galerias/cuarenta_mas_uno/1.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/2.galerias/cuarenta_mas_uno/2.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/2.galerias/nunca_mismo/NUNCA1.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/2.galerias/nunca_mismo/NUNCA2.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/2.galerias/opening/OPENING1.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/2.galerias/opening/OPENING2.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/2.galerias/p.general/1.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/2.galerias/p.general/2.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/2.galerias/p.artistas/1.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/3.arquitectura/arco/FUNDACION1.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/3.arquitectura/arco/FUNDACION2.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/3.arquitectura/espacios/ESPACIOS1.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/3.arquitectura/espacios/ESPACIOS2Y3.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/3.arquitectura/p.general/p.general.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/3.arquitectura/sala_cuarenta_mas_uno/sala_cua_uno.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/3.arquitectura/sala_vip/sala_vip.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/3.arquitectura/terraza/terraza.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/4.historia/historia_1.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/4.historia/historia_2.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/4.historia/historia_3.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/5.novedades/novedades_1.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/5.novedades/novedades_2.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/5.novedades/novedades_3.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/6.OtraTematicaChico/OtraTematicaChico.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/7.respuesta_si/respuesta_siI.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/8.pregunta_abierta/pregunta_abierta.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/9.puntuacion/puntuacion.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/10.despedidas/despedida_1.mp4",
  "https://feria.s3.us-east-2.amazonaws.com/video/chico/10.despedidas/despedida_2.mp4",
]